name: Generate Daily Report

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9:00 AM
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache reportData.json
        uses: actions/cache@v3
        with:
          path: reportData.json
          key: ${{ runner.os }}-reportData-${{ hashFiles('**/RedditPing.CLI/RedditPing.CLI.csproj') }}
          restore-keys: |
            ${{ runner.os }}-reportData-

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'


      - name: Build CLI
        run: dotnet build --configuration Release RedditPing.CLI/RedditPing.CLI.csproj || exit 1

      - name: Run CLI report generation
        run: dotnet run --project RedditPing.CLI -- report daily || exit 1

      - name: Upload Daily Report
        uses: actions/upload-artifact@v4
        with:
          name: DailyReport
          path: DailyReport.pdf
          if-no-files-found: error

