name: Generate Daily Report

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9:00 AM
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache reportData.json
        uses: actions/cache@v3
        with:
          path: reportData.json
          key: reportData-${{ github.run_id }}-${{ hashFiles('reportData.json') }}
          restore-keys: |
            reportData-

      - name: Set up .NET 9.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Build CLI
        run: dotnet build --configuration Release RedditPing.CLI/RedditPing.CLI.csproj || exit 1

      - name: Run CLI report generation
        run: dotnet run --project RedditPing.CLI -- report generate || exit 1

      - name: Upload Daily Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: DailyReport
          path: DailyReport.pdf
          if-no-files-found: error

      - name: Upload Daily Report to Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: daily-reports
          name: "Daily Reports"
          prerelease: false
          files: DailyReport.pdf

      - name: Clear Report Data for Next Cycle
        if: success()
        run: dotnet run --project RedditPing.CLI -- report delete-data

      - name: Save Cleared reportData.json to Cache
        if: success()
        uses: actions/cache@v3
        with:
          path: reportData.json
          key: reportData-clean-${{ github.run_id }}
