name: Generate Daily Report

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9:00 AM
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # Cache reportData.json
      - name: Restore reportData.json from cache
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: reportData.json
          key: report-data
          restore-keys: report-data-

      - name: Download latest reportData.json
        uses: actions/download-artifact@v4
        with:
          name: reportData
          path: reportData  # Ensure it downloads to a folder
        continue-on-error: true  

      - name: Extract reportData.json
        run: |
          if [ -f "reportData/reportData.json" ]; then
            mv reportData/reportData.json .
          else
            echo "{}" > reportData.json  # Creates an empty JSON if missing
          fi

      - name: Build CLI
        run: dotnet build --configuration Release RedditPing.CLI/RedditPing.CLI.csproj || exit 1

      - name: Run CLI report generation
        run: dotnet run --project RedditPing.CLI -- report daily || exit 1

      - name: Upload Daily Report
        uses: actions/upload-artifact@v4
        with:
          name: DailyReport
          path: DailyReport.pdf
          if-no-files-found: error

      # Save updated reportData.json to cache
      - name: Save reportData.json to cache
        uses: actions/cache@v3
        with:
          path: reportData.json
          key: report-data
